version: "3.9"
services:
  nest-crud-server:
    image: postgres:13
    ports:
      - 8000:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - nest-projects
  nest-crud-test-server:
    image: postgres:13
    ports:
      - 8001:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - nest-projects
networks:
  nest-projects:
